"""empty message

Revision ID: 6370e7a01ef5
Revises: eac30a23c7a1
Create Date: 2024-04-22 19:43:03.868193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6370e7a01ef5"
down_revision: Union[str, None] = "eac30a23c7a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("character", sa.Column("family_fate_id", sa.Integer(), nullable=True))
    op.add_column("character", sa.Column("parent_fate_id", sa.Integer(), nullable=True))
    op.add_column(
        "character", sa.Column("family_situation_id", sa.Integer(), nullable=True)
    )
    op.add_column("character", sa.Column("friend_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "character", "familysituation", ["family_situation_id"], ["id"]
    )
    op.create_foreign_key(None, "character", "parentfate", ["parent_fate_id"], ["id"])
    op.create_foreign_key(None, "character", "familyfate", ["family_fate_id"], ["id"])
    op.create_foreign_key(None, "character", "friend", ["friend_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "character", type_="foreignkey")
    op.drop_constraint(None, "character", type_="foreignkey")
    op.drop_constraint(None, "character", type_="foreignkey")
    op.drop_constraint(None, "character", type_="foreignkey")
    op.drop_column("character", "friend_id")
    op.drop_column("character", "family_situation_id")
    op.drop_column("character", "parent_fate_id")
    op.drop_column("character", "family_fate_id")
    # ### end Alembic commands ###
