"""empty message

Revision ID: 6d84ea605ba5
Revises: 1ffc959fc9c2
Create Date: 2024-07-15 22:02:55.768122

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d84ea605ba5"
down_revision: Union[str, None] = "1ffc959fc9c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_event_association",
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["importantevent.id"],
        ),
    )
    op.drop_constraint(
        "importantevent_character_id_fkey", "importantevent", type_="foreignkey"
    )
    op.drop_column("importantevent", "character_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "importantevent",
        sa.Column("character_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "importantevent_character_id_fkey",
        "importantevent",
        "character",
        ["character_id"],
        ["id"],
    )
    op.drop_table("character_event_association")
    # ### end Alembic commands ###
