"""empty message

Revision ID: a56c7f2a3773
Revises: efd3c52facde
Create Date: 2024-07-24 20:31:41.997213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a56c7f2a3773"
down_revision: Union[str, None] = "efd3c52facde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attribute",
        "name",
        existing_type=sa.VARCHAR(length=15),
        type_=sa.String(length=25),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attribute",
        "name",
        existing_type=sa.String(length=25),
        type_=sa.VARCHAR(length=15),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
