"""empty message

Revision ID: 73fea24744c2
Revises: af6d9dae9a0b
Create Date: 2024-08-05 20:09:18.860130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73fea24744c2"
down_revision: Union[str, None] = "af6d9dae9a0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "character",
        sa.Column("gender", sa.Enum("MALE", "FEMALE", name="gendertype"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("character", "gender")
    # ### end Alembic commands ###
