"""empty message

Revision ID: a598e58eb6ac
Revises: a56c7f2a3773
Create Date: 2024-07-24 20:34:14.379744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a598e58eb6ac"
down_revision: Union[str, None] = "a56c7f2a3773"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "skill",
        "name",
        existing_type=sa.VARCHAR(length=25),
        type_=sa.String(length=40),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "skill",
        "name",
        existing_type=sa.String(length=40),
        type_=sa.VARCHAR(length=25),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
